version: '3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer
        restart: unless-stopped
        ports:
            - "7001:9000"
            - "8001:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /path/to/portainer:/data

    adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "68:68/tcp"
            - "68:68/udp"
            - "853:853/tcp"
            - "7002:80/tcp"
        volumes:
            - ${PWD}/AdGuardHome:/opt/adguardhome/conf

    jupyter:
        container_name: jupyter-notebook
        image: jupyter/base-notebook
        restart: unless-stopped
        ports:
            - "7004:8888"
        volumes:
            - /path/to/jupyter:/home/jovyan/work
            - ${PWD}/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
        environment:
            JUPYTER_ENABLE_LAB: "yes"

    btsync:
        container_name: btsync
        image: resilio/sync
        restart: unless-stopped
        ports:
            - "7005:8888"
            - "55555:55555"
        volumes:
            - /path/to/btsync:/mnt/sync
