version: '3'

services:
    jupyter:
        container_name: jupyter-notebook
        image: jupyter/base-notebook
        restart: unless-stopped
        ports:
            - "7004:8888"
        volumes:
            - /path/to/jupyter:/home/jovyan/work
            - ${PWD}/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
        environment:
            JUPYTER_ENABLE_LAB: "yes"
