version: '3'

services: 
    jira-software:
        container_name: jira-core
        restart: unless-stopped
        image: atlassian/jira-software:8.4.0
        environment: 
            - ATL_DB_DRIVER=org.postgresql.Driver
            - ATL_DB_TYPE=postgres72
            - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jira
            - ATL_JDBC_USER=${DB_USER}
            - ATL_JDBC_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./Volumes/jira-software:/var/atlassian/application-data/jira
        ports: 
            - "80:8080"
        networks: 
            jira-bundle:
                aliases: 
                    - jira-software
        depends_on: 
            - postgresql
            - confluence
    
    confluence:
        container_name: confluence-server
        restart: unless-stopped
        image: atlassian/confluence-server:6.6.3-alpine-adoptopenjdk8
        environment: 
            - ATL_DB_TYPE=postgresql
            - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/confluence
            - ATL_JDBC_USER=${DB_USER}
            - ATL_JDBC_PASSWORD=${DB_PASSWORD}
        volumes: 
            - ./Volumes/confluence-server:/var/atlassian/application-data/confluence
        ports:
            - "8090:8090"
            - "8091:8091"
        networks:
            jira-bundle:
                aliases: 
                    - confluence
        depends_on: 
            - postgresql

    postgresql:
        container_name: postgresql
        restart: unless-stopped
        image: postgres:9.6.2
        volumes: 
            - ./Volumes/postgresql:/var/lib/postgresql/data
            - ./pg-init-script.sh:/docker-entrypoint-initdb.d/pg-init-script.sh
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_MULTIPLE_DATABASES=jira,confluence
        networks: 
            jira-bundle:
                aliases: 
                    - postgresql

networks:
    jira-bundle:
