version: '3'

services: 
    jira-software:
        container_name: jira-core
        restart: unless-stopped
        image: atlassian/jira-software:8.4.0
        environment: 
            - ATL_DB_DRIVER=com.mysql.jdbc.Driver
            - ATL_DB_TYPE=mysql
            - ATL_JDBC_URL=jdbc:mysql://mysql:3306/jira?useSSL=false
            - ATL_JDBC_USER=${DB_USER}
            - ATL_JDBC_PASSWORD=${DB_PASSWORD}

        volumes:
            - ./Volumes/jira-software:/var/atlassian/application-data/jira
            - ./mysql-connector-java-5.1.48.jar:/opt/atlassian/jira/lib/mysql-connector-java-5.1.48.jar
        ports: 
            - "80:8080"
        networks: 
            jira-bundle:
                aliases: 
                    - jira-software
        depends_on: 
            - mysql
            - confluence
    
    confluence:
        container_name: confluence-server
        restart: unless-stopped
        image: atlassian/confluence-server:6.6.3-alpine-adoptopenjdk8
        environment: 
            - ATL_DB_TYPE=mysql
            - ATL_JDBC_URL=jdbc:mysql://mysql:3306/confluence?useSSL=false
            - ATL_JDBC_USER=${DB_USER}
            - ATL_JDBC_PASSWORD=${DB_PASSWORD}
        volumes: 
            - ./Volumes/confluence-server:/var/atlassian/application-data/confluence
            - ./mysql-connector-java-5.1.48.jar:/opt/confluence/jira/lib/mysql-connector-java-5.1.48.jar
        ports:
            - "8090:8090"
            - "8091:8091"
        networks:
            jira-bundle:
                aliases: 
                    - confluence
        depends_on: 
            - mysql

    mysql:
        container_name: mysql
        restart: unless-stopped
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3306:3306"
        volumes: 
            - ./Volumes/mysql:/var/lib/mysql
            - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
        networks: 
            jira-bundle:
                aliases: 
                    - mysql 

networks:
    jira-bundle:
